### PR TITLE
README: Prevent Firefox from flagging Macro Deck as a security risk

### PR DESCRIPTION
**Pull request by Chefski**
### Description

Prevents Firefox from marking the links as a Potential Security Risk (not sure if it happens on other
image

### Motivation and Context

It'll make more convenient to press on a link that doesn't have a warning.

### How Has This Been Tested?

Tested OS(s): 
I opened the link and it shows the warning. I tested it on Mac and Windows and both OS's have this issue and it fixes the issue.

### Types of changes

- Documentation change (a change to documentation pages)

### Checklist:

-  [x] I have read the [Contributing Guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing-Guidelines).
-  [ ] All commit messages are properly formatted and commits squashed where appropriate.
-  [ ] My code is not on `master` or a `release/*` branch.
-  [x] The code has been tested.
-  [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Please amend your commit to follow our [commit guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing-Guidelines#commit-guidelines)

**Comment by Chefski** [comment]
Changed it. Is this ok?

**Comment by Chefski** [comment]
How do I wrap the message? Do I Just `\n` at the end of the message?

**Comment by RytoEX** [comment]
> How do I wrap the message? Do I Just `\n` at the end of the message?

Line break at 72 characters.

**Comment by Chefski** [comment]
Backticks don't seem to remove the link. Unless I'm using the wrong backticks

**Comment by Chefski** [comment]
Ok fixed it. Replaced the full stop with one dot leader

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nit: "Firefox" is one word. Do not line break in the middle of it. Use line breaks as if you were word wrapping without hyphenated line-endings.

**Comment by Chefski** [comment]
Sorry, thought it might have to be exactly at 72 characters.

**Review by RytoEX — APPROVED** [review]
Ran into this today. Seems fine.

**Pull request merged**
